### ISSUE TITLE
Drop support for Gitpod now they dropped support for self-hosting?

### ISSUE THREAD

**Issue by n1k0** [MTES-MCT/ecobalyse#186]
> We no longer actively support self hosting Gitpod

https://www.gitpod.io/blog/introducing-gitpod-dedicated

I think we shouldn't promote nor recommend the tool anymore.

As a side note, I don't use it myself. Is anybody currently using the Gitpod setup documented in the README?

Thoughts? @magopian @paulboosz

**Comment by magopian** [comment]
Gitpod was very useful at the beginning of our foray into brightway with @paulboosz , but we haven't used it since, so I guess when can now remove the support?

On a side note, we never used gitpod's "self hosting", so i don't think this announcement concerns us at all.
