### ISSUE TITLE
[API] Error in the calculation of the sum of materials

### ISSUE THREAD

**Issue by cerve** [MTES-MCT/ecobalyse#226]
Due to a javascript issue, in some cases, the API materials sum check does not work.

Using 

`materials[]=coton;0.7&materials[]=acrylique-r;0.2&materials[]=jute;0.1` 

the API returns this error 

`{"errors":{"materials":"La somme des parts de matières doit être égale à 1 (ici : 0.9999999999999999)"}}`

In this case, we have 0.7 + 0.2 + 0.1 and it should not give error.

**Comment by magopian** [comment]
Thanks for the feedback! We've fixed this in #242 ;)

Heads up: we're also looking to change all the "percentages" inputs in the API from float (between 0 and 1) to integer (between 0 and 100). There will be an entry in the changelog when that happens (soon hopefully!)
