### ISSUE TITLE
Ennoblissement : question (doute) sur le calcul (pr gwp)

### ISSUE THREAD

**Issue by antoineverger1** [MTES-MCT/ecobalyse#313]
Chère équipe Ecobalyse, 

je comparais les calculs de notre propre outil et j'ai du mal à retomber sur mes pates quant au calcul de l'ennoblissement dans Ecobalyse. Je m'explique avec une exemple concret (voir screenshot, tshirt 100% coton, 0,5kg, tout en Chine!)
![image](https://github.com/MTES-MCT/ecobalyse/assets/43539846/006e46d3-d678-443f-a9ac-87678510ff2e)

L'énergie pour la chaleur est 21,54 MJ, pour l'électricité 1,43 kWh. En faisant le calcul à la main (pr le gwp spécifiquement), j'obtiens 21,54 * 0,1068 (https://github.com/MTES-MCT/ecobalyse/blob/662c8e6e7aecb2acb85fa232d99873374bec0c3a/data/textile/ior_correction/processes_pre_correction.json#L5890) + 1,43 * 1.057 (https://github.com/MTES-MCT/ecobalyse/blob/662c8e6e7aecb2acb85fa232d99873374bec0c3a/data/textile/ior_correction/processes_pre_correction.json#L10C14-L10C21) ~= 3,81 kg co2e => dans le screenshot, vous pouvez voir que j'obtiens 6,6 kg co2e. 

Soit je me goure complètement, soit il me manque une information. J'aurais aimé aider à regarder en détail dans le code (et j'ai essayé) mais je ne suis pas "fluent" sur Elm malheureusement :( 

A bientot,

Antoine

**Comment by paulboosz** [comment]
Bonjour Antoine, 

Merci pour ta question très légitime.
Les processus de teinture et d'apprêt chimique consomment de la chaleur et de l'électricité, ce qui a indirectement un impact. Mais ces processus émettent aussi des gaz à effet de serre de manière directe. Il faut donc aussi ajouter ces impacts.
Tu peux retrouver les impacts dans ce fichier : 

- teinture sur étoffe, cch : 0.588 kg * 0.397 = 0.233 kgCO2e
- apprêt chimique, cch : 0.588 kg * 4.335 = 2.55 kgCO2e

En reprenant ton calcul on retrouve bien 3.81 + 0.233+ 2.55 = 6.6 kgCO2e

**Comment by antoineverger1** [comment]
Salut Paul, merci c'est super clair. 

Ca vaudrait le coup d'ajouter ces informations dans la version détaillée du simulateur pour des raisons de transparence (ou les sum-up dans le total chaleur et electricité).

Peux-tu me pointer vers le fichier que tu mentionnes (mais dont tu as omis le lien)?

**Comment by paulboosz** [comment]
oups oui désolé : https://github.com/MTES-MCT/ecobalyse/blob/662c8e6e7aecb2acb85fa232d99873374bec0c3a/public/data/processes.json

**Comment by antoineverger1** [comment]
J'ai toujours un souci par contre : 
si je décompose ton calcul 3.81 + 0.233+ 2.55 = 6.6 kgCO2e
3,81 vient de la teinture sur fil,
0,233 vient de la teinture sur etoffe,
et 2,55 vient des apprets chimiques.

=> pourquoi 2 niveaux de teinture, il ne devrait y en avoir qu'un seul non?

Si je regarde votre code (see screenshot), vous séparez dyeing, printing and finishing. Dans mon exemple ci-dessus, je n'ai aucune impression, par conséquent, je ne devrais avoir que 2 valeurs (dyeing aka teinture sur étoffe ds mon cas et finishing aka apprets) correct?

**Comment by antoineverger1** [comment]
Sorry, je crois que j'ai compris maintenant car j'avais mal lu le sujet autour des emissions directes et indirectes des procédés!
